### ISSUE TITLE
Including multiple regressors in temporal disaggregation

### ISSUE THREAD

**Issue by jennie-davies** [nbbrd/jdemetra-R#5]
When using the jd_td function I have tried to include two regressors using a formula such as y~x+z. I think it's only using the first variable. I have looked at the code and found the following line which seems to take the first series in the formula

xvar<-jd_tsvar(get(X.series.names[1], envir=environment(X.formula)), X.series.names[1])

Is it possible to include more than one regressor?

**Comment by palatej** [comment]
Corrected on Sep, 26
