### ISSUE TITLE
Including a jd_unregisterVariable function

### ISSUE THREAD

**Issue by jennie-davies** [nbbrd/jdemetra-R#6]
I have developed a function to remove user defined regressors - similar to jd_unregistercalendar. It may be useful to include in the package.

jd_unregisterVariable<- function(name, group){
  jd_context<-.jcall("ec/tstoolkit/algorithm/ProcessingContext", "Lec/tstoolkit/algorithm/ProcessingContext;", "getActiveContext")
  jd_vars<-.jcall(jd_context, "Lec/tstoolkit/timeseries/regression/TsVariables;", "getTsVariables", group)
  .jcall(jd_vars, "Z", "remove", name)
}

**Comment by palatej** [comment]
Added on Sep, 26
